#!/bin/zsh

source $WS_CFG_PATH/ws-shared

main () {
	local source_file="${WS_MY_PLUGIN_ROOT}/src/main.sh"
	local bin_file="${WS_CFG_PATH}/bin/swap-ctl"

	_ws_log verbose "Checking if file already exits ..."
	if [ -e "${WS_CFG_PATH}/bin/swap-ctl" ]; then
		_ws_log error "File at '${WS_CFG_PATH}/bin/swap-ctl' already exists."
		_ws_log warning "Please remove, and try installing again."

		return 127
	fi

	_ws_log verbose "Linking script ..."
	ln -s $(realpath -s ${source_file}) $(realpath -s ${bin_file})

	if [ -e "${bin_file}" ]; then
		chmod +x "${bin_file}"
	else
		_ws_log error "Could not create link!"

		return 127
	fi

	_ws_log verbose "Script read at '$(ls -lav ${bin_file})' ..."
	_ws_log warning "Installed swap-ctl."

	return 0
}

main $*
